/**
 * ============================================================================
 *  THE OFFLINE HELPER ("SERVICE WORKER"), WRITTEN AT BUILD TIME
 * ============================================================================
 * A service worker is a small script the browser keeps running next to the website. Ours keeps a
 * copy of the app's own files on the device, so:
 *  - the app still opens when the Wi-Fi drops, and
 *  - it can be installed as an app (phone home screen, desktop window). On an iPhone, an installed
 *    app keeps its own saved data, so Safari's "erase a website's data after 7 days without a visit"
 *    rule no longer wipes a schedule just because nobody opened it for a week.
 *
 * `vite.config.ts` calls `buildServiceWorker` after each build with the exact list of built files,
 * and writes the result to `sw.js`. Rules the generated script follows (each is tested):
 *  1. Pages (index.html) come from the INTERNET FIRST, so a new version always reaches people; the
 *     saved copy is used only when offline.
 *  2. Other app files come from the saved copy first. Each build gives them new unique names
 *     (like `index-Co9hpARE.js`), so a saved copy can never be out of date.
 *  3. It only ever touches this app's own files: never another website, never the server
 *     (`/api/...`), never another site on the same github.io address (like `/netmon/`).
 *  4. Each build gets its own storage box ("cache"), and old boxes are deleted, so the device never
 *     fills up with old versions.
 */

/** Every cache this app makes starts with this, so it never deletes another app's caches. */
export const CACHE_PREFIX = "shiftfit-";

/**
 * Returns the text of `sw.js`. `files` are the built files, relative to the site folder (for example
 * "index.html", "assets/index-Co9hpARE.js"); `version` is a code that changes with every build.
 */
export function buildServiceWorker(files: string[], version: string): string {
  return `// Generated by vite.config.ts from src/pwa/serviceWorker.ts. Do not edit by hand.
const CACHE = ${JSON.stringify(CACHE_PREFIX + version)};
const FILES = ${JSON.stringify(files)};
// Turns "assets/x.js" into a full address inside this app's folder (e.g. https://host/cadence/assets/x.js).
const inApp = (file) => new URL(file, self.registration.scope).href;
// Find a saved file by its address alone. Web servers may label files "Vary: Origin", and the page asks
// for its script and stylesheet with an Origin note the saved copies were made without; without this,
// the browser treats them as different requests and goes online even when offline. Safe here: every
// saved file is one exact build's file, the same whoever asks for it.
const MATCH = { ignoreVary: true };

// Rule 4: a new version saves all of its files in a fresh box, then takes over straight away.
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(FILES.map(inApp))).then(() => self.skipWaiting()),
  );
});

// Rule 4: throw away this app's boxes from older versions.
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(${JSON.stringify(CACHE_PREFIX)}) && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Rule 3: only plain downloads of this app's own files; everything else goes straight to the internet.
  if (request.method !== "GET") return;
  if (!request.url.startsWith(self.registration.scope)) return;
  if (new URL(request.url).pathname.includes("/api/")) return;

  // Rule 1: pages from the internet first; the saved copy only if that fails (offline).
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match(inApp("index.html"), MATCH)));
    return;
  }
  // Rule 2: saved copy first, internet if this file was never saved.
  event.respondWith(caches.match(request, MATCH).then((saved) => saved || fetch(request)));
});
`;
}
